name: JSDoc Action

on:
    push:
        branches: ['main', 'bug-*', 'feature-*', 'WIP-*']
    pull_request:
        branches: ['main', 'bug-*', 'feature-*', 'WIP-*']

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: JSDocs Generation
              uses: andstor/jsdoc-action@v1
              with:
                  source_dir: ./source
                  output_dir: ./source/out
                  config_file: jsdoc.json
                  template: minami
                  recurse: true
                  front_page: README.md
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ github.token }}
                  publish_dir: ./source