name: JSDoc Action

on:
  push:
    branches: ["main", "bug-*", "feature-*", "WIP-*"]
  pull_request:
    branches: ["main", "bug-*", "feature-*", "WIP-*"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: JSDocs Generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./docs
          config_file: ./conf.json
          template: minami
          recurse: true
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs