name: JSDoc Action

on:
  push:
    branches: ["main", "bug-*", "feature-*", "WIP-*"]
  pull_request:
    branches: ["main", "bug-*", "feature-*", "WIP-*"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: JSDocs Generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source
          output_dir: ./source/docs
          config_file: jsdoc.json
          template: minami
          front_page: README.md

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
        # with:
        #   deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        #   publish_dir: ./docs/