name: Generate Docs and deploy to gh-pages branch
run-name: Generating Documentation and Refactoring the page for gh-pages branch 🚀
on: 
  push:
    branches: ["main"]
jobs:
  merge_main:
    runs-on: ubuntu-latest
    steps:
      - name: Merge main to gh-pages
        run: |
          git config --global user.name 'Github pages action'
          git config --global user.email 'pages@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY

          git fetch origin
          
          git checkout main
          git merge origin/main

          git checkout gh-pages
          git merge origin/gh-pages

          git merge -X theirs main
          git commit --allow-empty -m "Merged main branch to gh-pages"

          git push origin gh-pages
  move_html_files-compile_JSDocs:
    needs: merge_main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: Copy html files
        run: cp ./source/html/* ./
      - name: Update paths in html files
        run: |
          sed -i 's/\/source/.\/source/' *.html
      - name: Update paths in js files
        run: |
          sed -i 's/\"\/source/\".\/source/' source/scripts/*.js
      - name: JSDocs Generation
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: source
          output_dir: docs
          template: minami
          recurse: true
      - name: Remove Timestamps
        run: |
          sed -i -E 's/[0-9]{2}:[0-9]{2}:[0-9]{2}//' docs/*.html
      - name: commit and push changes to gh-pages branch
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Github pages action'
            git config --global user.email 'pages@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            git add .
            git commit --allow-empty -m "Updated html files in root and generated Docs"
            git push
          fi